### ISSUE TITLE
Support exclusive versions for certain clusters

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-prov-sys#112]
We need the capability to allow some organizations to run some versions while preventing all other organizations from running the same versions.  The reason for this is that the implementation of certain algorithms on the sliderule serverr side need to be kept private while under development.  So versions of the sliderule servers with those algorithms implemented need to be constrained to only be allowed to be run by certain organizations.

One idea Carlos came up with for accomplishing this is to have a file in each terraform version directory (sliderule/prov-sys/cluster_tf_versions/<version>) that lists all the orgs that can use that version.  If the file does not exist then the version is available to all organizations.  If the file does exist, then the organization must be in the list in order to display that version as an option.

**Comment by cugarteblair** [comment]
added in v3.2.14
