### ISSUE TITLE
Pull S3 terraform on every cluster start

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-prov-sys#125]
For clusters that use certain version tags - `latest`, `v3`, `v4`, etc - the tags are updated continually behind the scenes; and the intention is that as these tags are updated, they are immediately available to the cluster the next time the cluster is started.

Currently, the provisioning system will only pull the terraform from S3 when the `configure` command is executed.  This needs to change so that the terraform is pulled every time a cluster starts.

**Comment by cugarteblair** [comment]
implemented in v3.3.4
