### ISSUE TITLE
Cluster did not shutdown when capacity request expired

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-prov-sys#130]
On 11/1 a capacity request for 20 nodes was entered for the "uw" cluster.  It appears that the request should have expired the next day, but when the expiration came, not action was taken by the provisioning system, and the cluster was left running.  Also, there were no entries in the provisioning tab.

![image](https://github.com/ICESat2-SlideRule/sliderule-prov-sys/assets/54070345/98817359-0c8f-4e3b-9e29-067946289c3b)

**Comment by jpswinski** [comment]
Is it possible that the provisioning system was updated while a capacity request was active, and the expiration of that capacity request was not acted on by the new deployment of the provisioning system?

**Comment by cugarteblair** [comment]
fixed v3.3.3
