### ISSUE TITLE
Cluster failed to be deployed

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-prov-sys#95]
The utexas cluster had never been deployed with the new provsys code.  When running from a Python script and requesting the desired nodes to be 1, the request shows up in the Pending Capacity Requests, but no action is taken from it.

**Comment by jpswinski** [comment]
![image](https://github.com/ICESat2-SlideRule/sliderule-prov-sys/assets/54070345/d624bf8d-bc25-4696-8897-6405a8cb3046)

**Comment by jpswinski** [comment]
After clicking "Configure", it ran a "Processing Configure" request.  But still, when subsequent capacity requests were made, nothing happened.

**Comment by cugarteblair** [comment]
I did a destroy then refresh then I was able to deploy.

**Comment by cugarteblair** [comment]
closing this. The one time transition from the older version of prov-sys to the new required destroy. moving forward that is not the case
