### ISSUE TITLE
Streamline email verification flow

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-prov-sys#96]
After creating a new account it is not obvious that the email on that account needs to be verified before requesting membership to an organization.  When the membership is requested, the user is prompted to verify their email address.  When the email address is verified, they then have to go back and re-request membership to the organization

I recommend either making it a part of the Sign Up process to verify the email address, or make it so that if someone requests membership and is prompted to verify their email address, once verified the membership request automatically goes through.

**Comment by cugarteblair** [comment]
completed in V3.2.8
